class_stereotype:
  name: Subkind
  parent: RigidSortal
  provides_identity: false
  identity_principle: simple
  rigidity: rigid
  dependency: optional
  supertypes:
  - Kind
  - Subkind
  - Collective
  - Quantity
  - Relator
  - Category
  - Mixin
  subtypes:
  - Subkind
  - Phase
  - Role
  forbidden_associations:
  - Structuration
  abstract: undefined
